#!/usr/bin/env bash
set -euo pipefail

# Generated by mkfrinZ.sh; --length is the PP value from each .cor header.
frinZ --input cor/YAMAGU32_YAMAGU34_2021156183500_all.cor --length 1440 --loop 1
frinZ --input cor/YAMAGU34_HITACH32_2023262084600_x.cor --length 120 --loop 1
frinZ --input cor/YAMAGU34_YAMAGU34_2023262084600_x.cor --length 120 --loop 1
frinZ --input cor/YAMAGU34_HITACH32_2023262102100_all.cor --length 120 --loop 1
frinZ --input cor/YAMAGU34_HITACH32_2023262102100_x.cor --length 120 --loop 1
frinZ --input cor/YAMAGU34_HITACH32_2023262102100_x_mkcor.cor --length 120 --loop 1
frinZ --input cor/YAMAGU34_YAMAGU34_2023262102100_x.cor --length 120 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2023266071400_x.cor --length 60 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2023266071600_x.cor --length 900 --loop 1
frinZ --input cor/YAMAGU32_HITACH32_2025302081500_yi-corr.cor --length 3600 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU32_2025309150600T2025310003600_x_cormerge.cor --length 28800 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2025309150600T2025310003600_x_cormerge.cor --length 28800 --loop 1
frinZ --input cor/YAMAGU34_YAMAGU34_2025309150600T2025310003600_x_cormerge.cor --length 28800 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026019023400_c.cor --length 1440 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026019023400_x.cor --length 1440 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026019025900_c.cor --length 240 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026019025900_x.cor --length 240 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026019032400_c.cor --length 1800 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026019032400_x.cor --length 1800 --loop 1
frinZ --input cor/YAMAGU34_HITACH32_2026029082100T2026029152100_c_cormerge.cor --length 21600 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026104160000_x.cor --length 240 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026114083000_1.cor --length 10000 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU32_2026155123000_c.cor --length 240 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026155123000_c.cor --length 240 --loop 1
frinZ --input cor/YAMAGU34_YAMAGU34_2026155123000_c.cor --length 240 --loop 1
frinZ --input cor/YAMAGU32_YAMAGU34_2026159003830_c.cor --length 600 --loop 1
