#!/usr/bin/env bash
# Generate an executable frinZ batch script from one or more .cor files.
#
# Usage:
#   ./mkfrinZ.sh YAMAGU32_YAMAGU34_*.cor
#
# The .cor file header stores PP (number of sectors) at byte offset 28.
# The first sector timestamp is the first four bytes after the 256-byte file
# header.  Files are ordered by that timestamp and PP becomes --length.

set -euo pipefail

if (( $# == 0 )); then
    printf 'Usage: %s FILE.cor [FILE.cor ...]\n' "${0##*/}" >&2
    exit 2
fi

output_script="exefrinZ.sh"
declare -a records=()

for input in "$@"; do
    if [[ ! -f "$input" ]]; then
        printf 'mkfrinZ.sh: file not found: %s\n' "$input" >&2
        exit 1
    fi

    # PP is a signed little-endian i32 at file-header byte offset 28.
    pp=$(od -An -td4 -j 28 -N 4 -- "$input" | awk '{print $1}')
    if [[ ! "$pp" =~ ^[0-9]+$ ]] || (( pp <= 0 )); then
        printf 'mkfrinZ.sh: invalid PP in %s: %s\n' "$input" "${pp:-<empty>}" >&2
        exit 1
    fi

    # The first sector begins at byte 256; its first i32 is Unix time.
    epoch=$(od -An -td4 -j 256 -N 4 -- "$input" | awk '{print $1}')
    if [[ ! "$epoch" =~ ^-?[0-9]+$ ]]; then
        printf 'mkfrinZ.sh: invalid timestamp in %s: %s\n' "$input" "${epoch:-<empty>}" >&2
        exit 1
    fi

    # TAB separates sort key, PP, and path.  Normal .cor names do not contain
    # newlines or tabs; reject those names rather than generating unsafe code.
    if [[ "$input" == *$'\t'* || "$input" == *$'\n'* ]]; then
        printf 'mkfrinZ.sh: filename contains a tab/newline: %s\n' "$input" >&2
        exit 1
    fi
    records+=("${epoch}"$'\t'"${pp}"$'\t'"${input}")
done

sorted_records=$(printf '%s\n' "${records[@]}" | sort -n -t $'\t' -k1,1 -k3,3)

{
    printf '#!/usr/bin/env bash\n'
    printf 'set -euo pipefail\n\n'
    printf '# Generated by mkfrinZ.sh; --length is the PP value from each .cor header.\n'
    while IFS=$'\t' read -r epoch pp input; do
        [[ -n "$input" ]] || continue
        printf 'frinZ --input %q --length %s --loop 1\n' "$input" "$pp"
    done <<< "$sorted_records"
} > "$output_script"

chmod +x "$output_script"
printf 'Generated %s (%d file(s))\n' "$output_script" "${#records[@]}"
